name: 'Publish to ESOUI'
description: 'Publish to ESOUI'
inputs:
  readme:
    description: 'Path of the readme file (not including folder path)'
    required: false
    default: 'README.md'
  changelog:
    description: 'Path of the changelog file (not including folder path)'
    required: false
    default: 'changelog.txt'
  EsoUIToken:
    description: 'Token from EsoUI'
    required: true
  EsoUIID:
    description: 'ID from EsoUI'
    required: true
  version:
    description: 'Version of the addon'
    required: true
  artifact:
    description: 'Build Artifact to upload'
    required: true
  dryRun:
    description: "Test your configuration against the ESOUI Web API"
    required: false
    default: false
runs:
  using: 'node14'
  main: 'index.js'
